### ISSUE TITLE
ARM下 Microsoft word 16.86 闪退

### ISSUE THREAD

**Issue by pzee** [QiuChenly/InjectLib#1]
### 检查事项

- [X] 已确保 InjectLib 更新到最新版本
- [X] 已确保软件版本为 InjectLib 支持范围

### 描述问题

注入最新的库后，Word(从Mac Store下载，版本是16.86) 闪退

### 最小复现

打开最新的库，执行秋城落叶_启动.command，对Word进行注入，注入成功后，一打开Word 就闪退

### 系统情况

- [ ] SIP 是否启动
- [ ] 是否为黑苹果（如果是黑苹果，请回答在下方标注了黑苹果的问题）

### 系统信息

```Shell
OS:Mac OS 14.5
CPU: ARM
内存：16G
```

### 期望行为

可以正常打开，并使用

### Crash Log

[Microsoft Word-2024-06-16-100109.ips.zip](https://github.com/user-attachments/files/15855909/Microsoft.Word-2024-06-16-100109.ips.zip)

**Comment by smomop** [comment]
顺带提一嘴banizip 365也是意外退出，x86正常

**Comment by xbclub** [comment]
补充下 outlook也闪退

**Comment by TrustDec** [comment]
Navicat Premium 也闪退

**Comment by QiuChenly** [comment]
崩溃的需要提交log日志文件。在“控制台”App中就可以提取到。

**Comment by xbclub** [comment]
[outlook.log](https://github.com/user-attachments/files/15948616/outlook.log)


> 崩溃的需要提交log日志文件。在“控制台”App中就可以提取到。

附件为 outlook崩溃日志

**Comment by smomop** [comment]
> 顺带提一嘴banizip 365也是意外退出，x86正常

附上bandizip ARM版崩溃日志
[bandizip.log](https://github.com/user-attachments/files/15948764/bandizip.log)

**Comment by QiuChenly** [comment]
现在你们还闪退吗？

**Comment by xbclub** [comment]
> 现在你们还闪退吗？

outlook仍然闪退，下附日志
[outlook2.log](https://github.com/user-attachments/files/16121885/outlook2.log)

**Comment by QiuChenly** [comment]
> > 现在你们还闪退吗？
> 
> outlook 仍然闪退，下附日志 [outlook2.log](https://github.com/user-attachments/files/16121885/outlook2.log)

这个没有做适配 请知悉。目前适配并在以下APP测试通过：Excel Word Point

**Comment by xbclub** [comment]
> > > 现在你们还闪退吗？
> > 
> > 
> > outlook 仍然闪退，下附日志 [outlook2.log](https://github.com/user-attachments/files/16121885/outlook2.log)
> 
> 这个没有做适配 请知悉。目前适配并在以下APP测试通过：Excel Word Point

这三个倒是没问题，outlook可以做适配吗，我看软件能识别到outlook做注入

**Comment by QiuChenly** [comment]
早期版本是可以的 但是目前我并没有做跟进处理 并且反应这个outlook的人也不多 所以没有优先处理 后面会跟进的

**Comment by TrustDec** [comment]
这是Navicat Premium Version 17.0.10 (207)的崩溃日志
[Navicat Premium-2024-07-11-222947.ips.zip](https://github.com/user-attachments/files/16179077/Navicat.Premium-2024-07-11-222947.ips.zip)

**Comment by QiuChenly** [comment]
> 这是Navicat Premium Version 17.0.10 (207)的崩溃日志 [Navicat Premium-2024-07-11-222947.ips.zip](https://github.com/user-attachments/files/16179077/Navicat.Premium-2024-07-11-222947.ips.zip)

<img width="1256" alt="image" src="https://github.com/QiuChenly/InjectLib/assets/24793281/9a5bb2be-8508-49df-b89b-c7e7962253e3">
这是即将上传的补丁注入后的结果，请稍后更新查看。
