### ISSUE TITLE
Craft

### ISSUE THREAD

**Issue by heiwhatsup** [QiuChenly/InjectLib#10]
### 检查事项

- [X] 已确保 InjectLib 更新到最新版本
- [X] 已确保软件版本为 InjectLib 支持范围

### 描述问题

Craft Setting A PUPU v2.8.6 (1704) 
dylib do Not take effect after injection

### 最小复现

After injection, the Free Plan still remain, and every time the App is restarted, a window will pop up telling "The current session has expired, please log in again."

### 系统情况

- [ ] SIP 是否启动
- [ ] 是否为黑苹果（如果是黑苹果，请回答在下方标注了黑苹果的问题）

### 系统信息

```Shell
macOS 13.6
Intel
```

### 期望行为

No Free Plan
No re-login frequently

**Comment by QiuChenly** [comment]
where from "Craft Setting A PUPU" ?

**Comment by heiwhatsup** [comment]
> where from "Craft Setting A PUPU" ?

i mean the application Craft downloaded from "setting a pupu".
