### ISSUE TITLE
setapp 无法正常使用 版本 3.37.1

### ISSUE THREAD

**Issue by glimpse-0201** [QiuChenly/InjectLib#12]
### 检查事项

- [X] 已确保 InjectLib 更新到最新版本
- [X] 已确保软件版本为 InjectLib 支持范围

### 描述问题

无法激活setapp 版本 3.37.1，注入成功有弹窗提示，打开后没有进入主页面，一段时间后弹出软件损坏提示重新安装。

### 最小复现

打开setapp后，点击说明页登陆正常跳转，主页不显示，一段时间后弹出软件损坏。

### 系统情况

- [ ] SIP 是否启动
- [ ] 是否为黑苹果（如果是黑苹果，请回答在下方标注了黑苹果的问题）

### 系统信息

```Shell
macos 14.5
intel i5
16gb
```

### 期望行为

正常进入程序主页

### 额外信息

尝试重新卸载重新注入，同样出现上述问题。
![image](https://github.com/user-attachments/assets/a21fa7a8-f8d0-441f-a48b-b5c51c8411fc)
弹窗正常出现
![image](https://github.com/user-attachments/assets/86fb327c-d958-46fb-88f8-786e53d6732c)
正常登陆
![image](https://github.com/user-attachments/assets/b15faa25-66b5-4f0d-b179-3df461c9d3a4)
出现异常

### Crash Log

没有崩溃日志

**Comment by QiuChenly** [comment]
这并不是真的损坏，而是软件内部增加了校验。有时间我会处理的。

**Comment by QiuChenly** [comment]
刚才测试了一下最新版本，你确定SetApp有关的App都注入了？一个是SetAppAgent 一个是 Setapp。

<img width="1289" alt="image" src="https://github.com/user-attachments/assets/ed76562d-ea82-4a74-a81b-cd3106d5d5bb">

**Comment by zhichucode** [comment]
好吧，我遇到的就是这个问题，请问解决了吗
