### ISSUE TITLE
Adobe Lightroom Classic 13.4 inject error

### ISSUE THREAD

**Issue by Zach677** [QiuChenly/InjectLib#16]
### 检查事项

- [X] 已确保 InjectLib 更新到最新版本
- [X] 已确保软件版本为 InjectLib 支持范围

### 描述问题

经过applecleaner完整卸载之后，在adobe CC重新下载
![CleanShot 2024-08-04 at 12 29 06](https://github.com/user-attachments/assets/a76a9975-4771-4b50-8890-d4a39b60b0b8)

![CleanShot 2024-08-04 at 12 36 01](https://github.com/user-attachments/assets/85b97c71-1f91-4521-a85d-118c7afda21f)

下载之后注入成功，并出现弹窗
![CleanShot 2024-08-04 at 12 36 39](https://github.com/user-attachments/assets/7529ddf4-734f-4ef8-8a72-54d04062f92d)
![CleanShot 2024-08-04 at 12 37 40@2x](https://github.com/user-attachments/assets/834d5148-c53f-4414-8528-65a780011eee)

但是仍然出现需要试用的弹窗，关闭这个就会导致lr关闭，license还是unknown
![CleanShot 2024-08-04 at 12 38 05@2x](https://github.com/user-attachments/assets/f65445e0-72e1-4215-bb3b-89836b8dabec)
![CleanShot 2024-08-04 at 12 38 17@2x](https://github.com/user-attachments/assets/82924273-e640-4653-8140-2c4b6e0cf4fb)

开启rosetta还是一样
![CleanShot 2024-08-04 at 12 48 00](https://github.com/user-attachments/assets/893add5a-269f-4c51-8ba3-c8656d0f0cae)

### 最小复现

如描述问题一栏

### 系统情况

- [ ] SIP 开着还是关着？
- [ ] 是否为黑苹果（如果是黑苹果，请回答在下方标注为黑苹果的问题）
- [ ] 黑苹果是否amfi_getout_of_my_way开了？或者操作过amfi相关属性和amfi相关quirk？

### 系统信息

```Shell
macOS: 15.1 beta (24B5009I)
m2pro
sip为开
```

### 期望行为

正常使用，不出现试用弹窗，license显示正常

**Comment by QiuChenly** [comment]
您的HUAWEI MateBook 似乎遇到了一些问题。
根据结果来看，似乎是arm64架构导致的不同问题，可以先尝试转译哦。
