### ISSUE TITLE
obsidian注入不生效(未成功显示激活)

### ISSUE THREAD

**Issue by kevinjoy89** [QiuChenly/InjectLib#17]
### 检查事项

- [X] 已确保 InjectLib 更新到最新版本
- [X] 已确保软件版本为 InjectLib 支持范围

### 描述问题

测试发现Obsidian无法激活, Obsidian版本为v1.6.7(Installer 1.5.12)
<img width="263" alt="image" src="https://github.com/user-attachments/assets/57d5c016-fba0-42ac-bd6c-39b5a59f1fcd">

### 最小复现

1. 安装Obsidian v1.6.7(即当前最新版)
2. 使用"秋城落叶_启动.command"进行注入，或者直接执行tool/obsidian.sh
<img width="676" alt="image" src="https://github.com/user-attachments/assets/75fbae27-31fb-4097-824a-d57237e3ef2f">

<img width="788" alt="image" src="https://github.com/user-attachments/assets/f19bfec1-2712-4cd0-b9b1-b177a4909841">

### 系统情况

- [ ] SIP 开着还是关着？
- [ ] 是否为黑苹果（如果是黑苹果，请回答在下方标注为黑苹果的问题）
- [ ] 黑苹果是否amfi_getout_of_my_way开了？或者操作过amfi相关属性和amfi相关quirk？

### 系统信息

```Shell
OS: MacOS Sonoma 14.5
CPU: M1
```

### 期望行为

显示正常激活

### 额外信息

tool/obsidian.sh中sed的var iY中的信息，Obsidian v1.6.7(即当前最新版)中无相关代码，在var En中存在license相关信息。已测试简单替换var En中的license相关信息无效。

**Comment by kevinjoy89** [comment]
> 已修复，请使用如下命令进行激活，请确保当前目录为InjectLib目录
> 
> ```shell
> cd tool/Obsidian
> sudo python3 Obsidian.py
> ```

实测可以激活了。

补充一个坑，供其他人参考：如果当前已安装版本同我的issue中描述，即Obsidian版本为v1.6.7(Installer 1.5.12)，使用`sudo python3 Obsidian.py`依然是无法激活的，请重新在官网下载最新版本(**Obsidian版本为v1.6.7(Installer 1.6.7)**)安装后运行上述脚本即可正常激活。

**Comment by shoudeyunkaijianyueming** [comment]
@X1a0He 最新版本1.7.7无法激活了，上述方法也不行
