### ISSUE TITLE
Unable to open Surge

### ISSUE THREAD

**Issue by fu-silent** [QiuChenly/InjectLib#18]
### 检查事项

- [x] 已确保 InjectLib 更新到最新版本
- [X] 已确保软件版本为 InjectLib 支持范围

### 描述问题

Unable to open Surge, crashes, never used it before

### 最小复现

Download and install the latest Surge installation package from https://nssurge.com/, download InjectLib from https://github.com/QiuChenly/InjectLib/ to my computer, run "秋城落叶_开始.command" to inject Surge.
Double-click to open "Surge.app", Surge exits, and a window pops up saying "Surge.app quit unexpectedly."

### 系统情况

- [ ] SIP 开着还是关着？
- [ ] 是否为黑苹果（如果是黑苹果，请回答在下方标注为黑苹果的问题）
- [ ] 黑苹果是否amfi_getout_of_my_way开了？或者操作过amfi相关属性和amfi相关quirk？

### 系统信息

```Shell
Mac BookAir 6,2
OS: MacOS 11.7.10
CPU: 1.7GHz dual-core Intel Core i7 (Turbo Boost up to 3.3GHz) with 4MB shared L3 cache (from support.apple.com)
Memory: 8 GB 1600 MHz DDR3
System Integrity Protection status: disabled.
```

### 期望行为

Double-click to open Surge.app to enter the main page and keep it running without crashing.

### 额外信息

The terminal displays "zsh: segmentation fault".

### Crash Log

[Surge_2024-08-06-115732_MacBookAir.crash.zip](https://github.com/user-attachments/files/16505112/Surge_2024-08-06-115732_MacBookAir.crash.zip)

**Comment by QiuChenly** [comment]
不支持Surge。这个里面的版本是给抽奖的人用的。
