### ISSUE TITLE
Sublime Text 4180 注入后无法启动

### ISSUE THREAD

**Issue by uclort** [QiuChenly/InjectLib#20]
### 检查事项

- [X] 已确保 InjectLib 更新到最新版本
- [X] 已确保软件版本为 InjectLib 支持范围

### 描述问题

Sublime Text 4180 注入成功，运行提示应用程序无法打开（截图）
![CleanShot 2024-08-12 at 11 15 01@2x](https://github.com/user-attachments/assets/e3681c43-642a-411d-adee-c8617a78ada6)

### 最小复现

官网下载安装包或者 brew 安装，然后注入 injectLib，打开 App 报错

### 系统情况

- [X] SIP 开着还是关着？
- [ ] 是否为黑苹果（如果是黑苹果，请回答在下方标注为黑苹果的问题）
- [ ] 黑苹果是否amfi_getout_of_my_way开了？或者操作过amfi相关属性和amfi相关quirk？

### 系统信息

```Shell
macOS 14.6
Apple M1
16GB
```

### 期望行为

正常运行

**Comment by QiuChenly** [comment]
手动签个名看看呢

**Comment by uclort** [comment]
> 手动签个名看看呢

`sudo xattr -c -r` 是这个命令么？试过了，效果一样。

**Comment by QiuChenly** [comment]
现在还是无法打开吗？我这里测试没有问题呢？你彻底卸载用脚本重新注入看看？

**Comment by uclort** [comment]
> 现在还是无法打开吗？我这里测试没有问题呢？你彻底卸载用脚本重新注入看看？

还是不行，用`App Cleaner & Uninstaller`卸载`Sublime Text`，然后去[Sublime Text 管网](https://www.sublimetext.com/download)下载安装包，重新注入的，还是提示无法打开，`sudo xattr -c -r`命令也尝试了。

**Comment by jas0nxu** [comment]
> > 现在还是无法打开吗？我这里测试没有问题呢？你彻底卸载用脚本重新注入看看？
> 
> 还是不行，用`App Cleaner & Uninstaller`卸载`Sublime Text`，然后去[Sublime Text 管网](https://www.sublimetext.com/download)下载安装包，重新注入的，还是提示无法打开，`sudo xattr -c -r`命令也尝试了。

是不行，codesign那一步出错了的，文件应该是损坏了，得等修复

**Comment by kian1990** [comment]
上个版本4169的没问题，用这个版本吧

**Comment by QiuChenly** [comment]
> > > 现在还是无法打开吗？我这里测试没有问题呢？你彻底卸载用脚本重新注入看看？
> > 
> > 
> > 还是不行，用`App Cleaner & Uninstaller`卸载`Sublime Text`，然后去[Sublime Text 管网](https://www.sublimetext.com/download)下载安装包，重新注入的，还是提示无法打开，`sudo xattr -c -r`命令也尝试了。
> 
> 是不行，codesign那一步出错了的，文件应该是损坏了，得等修复

看下报错呢

**Comment by minpsn** [comment]
> > > > 现在还是无法打开吗？我这里测试没有问题呢？你彻底卸载用脚本重新注入看看？
> > > 
> > > 
> > > 还是不行，用`App Cleaner & Uninstaller`卸载`Sublime Text`，然后去[Sublime Text 管网](https://www.sublimetext.com/download)下载安装包，重新注入的，还是提示无法打开，`sudo xattr -c -r`命令也尝试了。
> > 
> > 
> > 是不行，codesign那一步出错了的，文件应该是损坏了，得等修复
> 
> 看下报错呢

大佬，报internal error in Code Signing subsystem
