### ISSUE TITLE
setApp注入成功，但是安装的App，不能打开

### ISSUE THREAD

**Issue by Monkey0803** [QiuChenly/InjectLib#22]
### 检查事项

- [X] 已确保 InjectLib 更新到最新版本
- [X] 已确保软件版本为 InjectLib 支持范围

### 描述问题

![image](https://github.com/user-attachments/assets/f63957dc-c285-4838-bc54-6d4549d20d81)
注入成功了，登录成功了，在setapp里面安装了App，不能打开

### 最小复现

正常打开安装的App

### 系统情况

- [ ] SIP 开着还是关着？
- [ ] 是否为黑苹果（如果是黑苹果，请回答在下方标注为黑苹果的问题）
- [ ] 黑苹果是否amfi_getout_of_my_way开了？或者操作过amfi相关属性和amfi相关quirk？

### 系统信息

```Shell
os:15.1 Beta (24B5024e)
cpu:Apple M1
mem:16 GB
```

### 是否修改了nvram的内核启动参数（黑苹果）

否

### 是否使用了需要修改系统文件的工具（黑苹果）

否

### 期望行为

正常打开App

**Comment by QiuChenly** [comment]
重新注入这些app.
