### ISSUE TITLE
ulysses注入完无法正常进入，一直在开始界面转圈圈

### ISSUE THREAD

**Issue by 78wee** [QiuChenly/InjectLib#23]
### 检查事项

- [X] 已确保 InjectLib 更新到最新版本
- [X] 已确保软件版本为 InjectLib 支持范围

### 描述问题

ulysses注入完无法正常进入，一直在开始界面转圈圈 版本号Version 35.1 (77796)

### 最小复现

![doc_2024-08-16_14-01-26](https://github.com/user-attachments/assets/60dd4abb-f20f-4693-a8d3-81e5338112fe)

### 系统情况

- [ ] SIP 开着还是关着？
- [ ] 是否为黑苹果（如果是黑苹果，请回答在下方标注为黑苹果的问题）
- [ ] 黑苹果是否amfi_getout_of_my_way开了？或者操作过amfi相关属性和amfi相关quirk？

### 系统信息

```Shell
Processor 3.7 GHz 6-Core Intel Core Graphics Radeon Pro 580X 8 GB Memory 40 GB 2667 MHz DDRA Startup disk Macintosh HD
```

### 期望行为

可以正常使用

**Comment by X1a0He** [comment]
已修复
