### ISSUE TITLE
Bartender 5.0.54 激活失败

### ISSUE THREAD

**Issue by paststrange** [QiuChenly/InjectLib#24]
### 检查事项

- [X] 已确保 InjectLib 更新到最新版本
- [X] 已确保软件版本为 InjectLib 支持范围

### 描述问题

Bartender 5.0.54 激活失败。

### 最小复现

brew install bartender后，直接sudo python main.py注入，显示App处理完成。
<img width="1004" alt="image" src="https://github.com/user-attachments/assets/60cc5960-d6eb-4172-b1ac-794606397ae7">
<img width="839" alt="image" src="https://github.com/user-attachments/assets/d3978026-157d-43dd-9b49-ddcc03e52afd">
<img width="841" alt="image" src="https://github.com/user-attachments/assets/20f2a061-0ecb-43a7-b84b-7ee79a204a2c">

### 系统情况

- [X] SIP 开着还是关着？
- [ ] 是否为黑苹果（如果是黑苹果，请回答在下方标注为黑苹果的问题）
- [ ] 黑苹果是否amfi_getout_of_my_way开了？或者操作过amfi相关属性和amfi相关quirk？

### 系统信息

```Shell
OS: macOS 14.6.1 23G93 arm64
CPU: Apple M3 Pro
Memory: 5910MiB / 36864MiB
```

### 是否修改了nvram的内核启动参数（黑苹果）

否

### 是否使用了需要修改系统文件的工具（黑苹果）

否

### 期望行为

激活成功应该没有试用的字样。

### 额外信息

无

### Crash Log

无

**Comment by X1a0He** [comment]
已处理，等待更新
