### ISSUE TITLE
Bandizip 365 设置无法保存

### ISSUE THREAD

**Issue by junilask** [QiuChenly/InjectLib#26]
### 检查事项

- [X] 已确保 InjectLib 更新到最新版本
- [X] 已确保软件版本为 InjectLib 支持范围

### 描述问题

Bandizip 365 设置无法保存，一旦对设置作出改动，关闭设置窗口，设置就会还原

### 最小复现

一旦对设置作出改动，关闭设置窗口，设置就会还原

### 系统情况

- [X] SIP 开着还是关着？
- [ ] 是否为黑苹果（如果是黑苹果，请回答在下方标注为黑苹果的问题）
- [ ] 黑苹果是否amfi_getout_of_my_way开了？或者操作过amfi相关属性和amfi相关quirk？

### 系统信息

```Shell
OS：14.2.1 (23C71)
CPU：M1 MAX
Memory：32GB
```

### 期望行为

设置可以保存

**Comment by QiuChenly** [comment]
看起来像是一些配置项错误，这个小问题周末看看有空我会跟进一下，但是应该不会影响大部分情况。

**Comment by QiuChenly** [comment]
签名后丢失权限导致的，不影响暂不修复。
