### ISSUE TITLE
Surge5最高支持的版本是多少

### ISSUE THREAD

**Issue by hiCyoung** [QiuChenly/InjectLib#29]
### 检查事项

- [X] 已确保 InjectLib 更新到最新版本
- [X] 已确保软件版本为 InjectLib 支持范围

### 描述问题

测试了Surge5.7.4和5.7.3，注入后均打不开，直接崩溃，看之前的issue，回复说不支持Surge的最新版。所以问下Surge最高支持的版本是多少。

### 最小复现

注入了5.7.4和5.7.3版本，打开App均直接Crash。

### 系统情况

- [ ] SIP 开着还是关着？
- [ ] 是否为黑苹果（如果是黑苹果，请回答在下方标注为黑苹果的问题）
- [ ] 黑苹果是否amfi_getout_of_my_way开了？或者操作过amfi相关属性和amfi相关quirk？

### 系统信息

```Shell
CPU: Apple M1 Pro
Memory: 16 GB
OS: macOS 14.5 (23F79)
```

### 期望行为

使用该项目注入最高能支持的Surge版本。

### 额外信息

我已经尝试注入了5.7.4和5.7.3版本，打开App均直接Crash。

### Crash Log

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Surge [33551]
Path:                  /Applications/Surge.app/Contents/MacOS/Surge
Identifier:            com.nssurge.surge-mac
Version:               5.7.3 (2785)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               502

Date/Time:             2024-08-22 01:19:51.3479 +0800
OS Version:            macOS 14.5 (23F79)
Report Version:        12
Anonymous UUID:        80964B5B-EFFD-CCB2-0490-F4FAF5E0CD4E

Sleep/Wake UUID:       37CE0486-E95A-4CF3-BC49-2A374D86998C

Time Awake Since Boot: 170000 seconds
Time Since Wake:       4501 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x00000000829bde9a
Exception Codes:       0x0000000000000001, 0x00000000829bde9a

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [33551]

VM Region Info: 0x829bde9a is not in any region.  Bytes before following region: 2115854694
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      100b94000-100ba0000    [   48K] r-x/r-x SM=COW  /Applications/Surge.app/Contents/MacOS/Surge

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libobjc.A.dylib               	       0x18d8a1c08 objc_msgSend + 8
1   Surge                         	       0x100d0ae38 0x100b94000 + 1535544
2   91QiuChenly.dylib             	       0x101f4c7bc 0x101e14000 + 1279932
3   dyld                          	       0x18d90905c invocation function for block in dyld4::Loader::findAndRunAllInitializers(dyld4::RuntimeState&) const::$_0::operator()() const + 168
4   dyld                          	       0x18d9470d4 invocation function for block in dyld3::MachOAnalyzer::forEachInitializer(Diagnostics&, dyld3::MachOAnalyzer::VMAddrConverter const&, void (unsigned int) block_pointer, void const*) const + 172
5   dyld                          	       0x18d93a99c invocation function for block in dyld3::MachOFile::forEachSection(void (dyld3::MachOFile::SectionInfo const&, bool, bool&) block_pointer) const + 496
6   dyld                          	       0x18d8ea2fc dyld3::MachOFile::forEachLoadCommand(Diagnostics&, void (load_command const*, bool&) block_pointer) const + 300
7   dyld                          	       0x18d939930 dyld3::MachOFile::forEachSection(void (dyld3::MachOFile::SectionInfo const&, bool, bool&) block_pointer) const + 192
8   dyld                          	       0x18d93c208 dyld3::MachOFile::forEachInitializerPointerSection(Diagnostics&, void (unsigned int, unsigned int, bool&) block_pointer) const + 160
9   dyld                          	       0x18d946dc8 dyld3::MachOAnalyzer::forEachInitializer(Diagnostics&, dyld3::MachOAnalyzer::VMAddrConverter const&, void (unsigned int) block_pointer, void const*) const + 432
10  dyld                          	       0x18d905070 dyld4::Loader::findAndRunAllInitializers(dyld4::RuntimeState&) const + 524
11  dyld                          	       0x18d90b614 dyld4::JustInTimeLoader::runInitializers(dyld4::RuntimeState&) const + 36
12  dyld                          	       0x18d90545c dyld4::Loader::runInitializersBottomUp(dyld4::RuntimeState&, dyld3::Array<dyld4::Loader const*>&) const + 220
13  dyld                          	       0x18d905400 dyld4::Loader::runInitializersBottomUp(dyld4::RuntimeState&, dyld3::Array<dyld4::Loader const*>&) const + 128
14  dyld                          	       0x18d905400 dyld4::Loader::runInitializersBottomUp(dyld4::RuntimeState&, dyld3::Array<dyld4::Loader const*>&) const + 128
15  dyld                          	       0x18d9090ec dyld4::Loader::runInitializersBottomUpPlusUpwardLinks(dyld4::RuntimeState&) const::$_1::operator()() const + 116
16  dyld                          	       0x18d905628 dyld4::Loader::runInitializersBottomUpPlusUpwardLinks(dyld4::RuntimeState&) const + 380
17  dyld                          	       0x18d9284d8 dyld4::APIs::runAllInitializersForMain() + 464
18  dyld                          	       0x18d8eef7c dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 3156
19  dyld                          	       0x18d8ededc start + 1844

Thread 1:
0   libsystem_pthread.dylib       	       0x18dc71d20 start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	       0x18dc71d20 start_wqthread + 0

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x00000000829bde9a   x1: 0x00000001ee42dee3   x2: 0x0000000000000103   x3: 0x00000001fa684ec0
    x4: 0x0000000000000000   x5: 0x0000000000000000   x6: 0x00000000000000d6   x7: 0x0000000000000d70
    x8: 0x000000016f266580   x9: 0x0000000000000000  x10: 0x00000000000001c9  x11: 0xffffffffffffffff
   x12: 0x0000000000000080  x13: 0x00000000000007fd  x14: 0x0000000085865ffb  x15: 0x00000000000007fb
   x16: 0x000000018d8a1c00  x17: 0x00000001ffe66498  x18: 0x0000000000000000  x19: 0x00000000829bde9a
   x20: 0x000000016f266780  x21: 0x0000000000000015  x22: 0x00000000526af685  x23: 0x0000000101f8b7b0
   x24: 0x000000000000006a  x25: 0x0000000000000098  x26: 0x00000000b709217c  x27: 0x0000000101f8c240
   x28: 0x0000000101f5295c   fp: 0x000000016f266930   lr: 0x0000000100d0ae38
    sp: 0x000000016f2665f0   pc: 0x000000018d8a1c08 cpsr: 0x20001000
   far: 0x00000000829bde9a  esr: 0x92000006 (Data Abort) byte read Translation fault

Binary Images:
       0x1017b8000 -        0x1017cbfff com.diephouse.matt.MMMarkdown (1.0) <e26fee4b-77d3-3471-a034-5efd3d03c8bc> /Applications/Surge.app/Contents/Frameworks/MMMarkdown.framework/Versions/A/MMMarkdown
       0x10195c000 -        0x1019a3fff com.bugsnag.Bugsnag (6.27.0) <9eae454d-8523-3b48-8db3-b58352906945> /Applications/Surge.app/Contents/Frameworks/Bugsnag.framework/Versions/A/Bugsnag
       0x101a18000 -        0x101a5bfff org.sparkle-project.Sparkle (1.23.0) <ec5a5170-5391-3737-94af-65386955f8df> /Applications/Surge.app/Contents/Frameworks/Sparkle.framework/Versions/A/Sparkle
       0x101e14000 -        0x101f6ffff 91QiuChenly.dylib (*) <5aeeb666-e60e-37a8-b694-cbfd92d6d759> /Applications/Surge.app/Contents/Frameworks/91QiuChenly.dylib
       0x100b94000 -        0x1011d7fff com.nssurge.surge-mac (5.7.3) <04657493-b744-3c86-8ef4-e0c66701a38c> /Applications/Surge.app/Contents/MacOS/Surge
       0x18d898000 -        0x18d8e7d83 libobjc.A.dylib (*) <b326b2c3-1069-3d17-b49d-9dcb24efec6f> /usr/lib/libobjc.A.dylib
       0x18d8e8000 -        0x18d970a17 dyld (*) <37bbc384-0755-31c7-a808-0ed49e44dd8e> /usr/lib/dyld
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
       0x18dc70000 -        0x18dc7cfff libsystem_pthread.dylib (*) <386b0fc1-7873-3328-8e71-43269fd1b2c7> /usr/lib/system/libsystem_pthread.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.0G resident=0K(0%) swapped_out_or_unallocated=1.0G(100%)
Writable regions: Total=843.7M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=843.7M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Activity Tracing                   256K        1 
Kernel Alloc Once                   32K        1 
MALLOC                           830.2M       24 
MALLOC guard page                   96K        6 
STACK GUARD                       56.0M        3 
Stack                             9264K        3 
VM_ALLOCATE                         16K        1 
__AUTH                            1167K      251 
__AUTH_CONST                      22.6M      433 
__CTF                               824        1 
__DATA                            9186K      424 
__DATA_CONST                      22.4M      443 
__DATA_DIRTY                      1280K      146 
__FONT_DATA                          4K        1 
__LINKEDIT                       533.9M        6 
__OBJC_RO                         71.9M        1 
__OBJC_RW                         2199K        1 
__TEXT                           518.4M      469 
dyld private memory               4384K        4 
mapped file                       31.1M        2 
shared memory                       64K        4 
===========                     =======  ======= 
TOTAL                              2.1G     2225 

-----------
Full Report
-----------

{"app_name":"Surge","timestamp":"2024-08-22 01:19:51.00 +0800","app_version":"5.7.3","slice_uuid":"04657493-b744-3c86-8ef4-e0c66701a38c","build_version":"2785","platform":1,"bundleID":"com.nssurge.surge-mac","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 14.5 (23F79)","roots_installed":0,"name":"Surge","incident_id":"CF19DF7E-2AF7-4A32-93F6-5ABDA7297E3D"}
{
  "uptime" : 170000,
  "procRole" : "Background",
  "version" : 2,
  "userID" : 502,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro18,1",
  "coalitionID" : 56634,
  "osVersion" : {
    "train" : "macOS 14.5",
    "build" : "23F79",
    "releaseType" : "User"
  },
  "captureTime" : "2024-08-22 01:19:51.3479 +0800",
  "codeSigningMonitor" : 1,
  "incident" : "CF19DF7E-2AF7-4A32-93F6-5ABDA7297E3D",
  "pid" : 33551,
  "translated" : false,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2024-08-22 01:19:51.1196 +0800",
  "procStartAbsTime" : 4128320574498,
  "procExitAbsTime" : 4128325961748,
  "procName" : "Surge",
  "procPath" : "\/Applications\/Surge.app\/Contents\/MacOS\/Surge",
  "bundleInfo" : {"CFBundleShortVersionString":"5.7.3","CFBundleVersion":"2785","CFBundleIdentifier":"com.nssurge.surge-mac"},
  "storeInfo" : {"deviceIdentifierForVendor":"F9564AE5-757A-5E3E-9E71-3CFAED7739CB","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.nssurge.surge-mac",
  "crashReporterKey" : "80964B5B-EFFD-CCB2-0490-F4FAF5E0CD4E",
  "codeSigningID" : "com.nssurge.surge-mac",
  "codeSigningTeamID" : "",
  "codeSigningFlags" : 570425857,
  "codeSigningValidationCategory" : 10,
  "codeSigningTrustLevel" : 4294967295,
  "instructionByteStream" : {"beforePC":"HyAD1R8gA9UfIAPVHyAD1R8gA9UfIAPVHyAD1R8gA9UfAADxzQMAVA==","atPC":"DgBA+dDNfZLqAwCqKlzt8lAZwdrvAxCqCgpA+Uv9cNNKvUCSLAALCg=="},
  "wakeTime" : 4501,
  "sleepWakeUUID" : "37CE0486-E95A-4CF3-BC49-2A374D86998C",
  "sip" : "enabled",
  "vmRegionInfo" : "0x829bde9a is not in any region.  Bytes before following region: 2115854694\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      __TEXT                      100b94000-100ba0000    [   48K] r-x\/r-x SM=COW  \/Applications\/Surge.app\/Contents\/MacOS\/Surge",
  "exception" : {"codes":"0x0000000000000001, 0x00000000829bde9a","rawCodes":[1,2191253146],"type":"EXC_BAD_ACCESS","signal":"SIGSEGV","subtype":"KERN_INVALID_ADDRESS at 0x00000000829bde9a"},
  "termination" : {"flags":0,"code":11,"namespace":"SIGNAL","indicator":"Segmentation fault: 11","byProc":"exc handler","byPid":33551},
  "vmregioninfo" : "0x829bde9a is not in any region.  Bytes before following region: 2115854694\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      __TEXT                      100b94000-100ba0000    [   48K] r-x\/r-x SM=COW  \/Applications\/Surge.app\/Contents\/MacOS\/Surge",
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":6405622,"threadState":{"x":[{"value":2191253146},{"value":8292327139,"objc-selector":"policy"},{"value":259},{"value":8496107200,"symbolLocation":128,"symbol":"vtable for dyld4::LibSystemHelpers"},{"value":0},{"value":0},{"value":214},{"value":3440},{"value":6159754624},{"value":0},{"value":457},{"value":18446744073709551615},{"value":128},{"value":2045},{"value":2240176123},{"value":2043},{"value":6669605888,"symbolLocation":0,"symbol":"objc_msgSend"},{"value":8588256408},{"value":0},{"value":2191253146},{"value":6159755136},{"value":21},{"value":1382741637},{"value":4328044464},{"value":106},{"value":152},{"value":3070828924},{"value":4328047168},{"value":4327811420}],"flavor":"ARM_THREAD_STATE64","lr":{"value":4308643384},"cpsr":{"value":536875008},"fp":{"value":6159755568},"sp":{"value":6159754736},"esr":{"value":2449473542,"description":"(Data Abort) byte read Translation fault"},"pc":{"value":6669605896,"matchesCrashFrame":1},"far":{"value":2191253146}},"queue":"com.apple.main-thread","frames":[{"imageOffset":39944,"symbol":"objc_msgSend","symbolLocation":8,"imageIndex":5},{"imageOffset":1535544,"imageIndex":4},{"imageOffset":1279932,"imageIndex":3},{"imageOffset":135260,"symbol":"invocation function for block in dyld4::Loader::findAndRunAllInitializers(dyld4::RuntimeState&) const::$_0::operator()() const","symbolLocation":168,"imageIndex":6},{"imageOffset":389332,"symbol":"invocation function for block in dyld3::MachOAnalyzer::forEachInitializer(Diagnostics&, dyld3::MachOAnalyzer::VMAddrConverter const&, void (unsigned int) block_pointer, void const*) const","symbolLocation":172,"imageIndex":6},{"imageOffset":338332,"symbol":"invocation function for block in dyld3::MachOFile::forEachSection(void (dyld3::MachOFile::SectionInfo const&, bool, bool&) block_pointer) const","symbolLocation":496,"imageIndex":6},{"imageOffset":8956,"symbol":"dyld3::MachOFile::forEachLoadCommand(Diagnostics&, void (load_command const*, bool&) block_pointer) const","symbolLocation":300,"imageIndex":6},{"imageOffset":334128,"symbol":"dyld3::MachOFile::forEachSection(void (dyld3::MachOFile::SectionInfo const&, bool, bool&) block_pointer) const","symbolLocation":192,"imageIndex":6},{"imageOffset":344584,"symbol":"dyld3::MachOFile::forEachInitializerPointerSection(Diagnostics&, void (unsigned int, unsigned int, bool&) block_pointer) const","symbolLocation":160,"imageIndex":6},{"imageOffset":388552,"symbol":"dyld3::MachOAnalyzer::forEachInitializer(Diagnostics&, dyld3::MachOAnalyzer::VMAddrConverter const&, void (unsigned int) block_pointer, void const*) const","symbolLocation":432,"imageIndex":6},{"imageOffset":118896,"symbol":"dyld4::Loader::findAndRunAllInitializers(dyld4::RuntimeState&) const","symbolLocation":524,"imageIndex":6},{"imageOffset":144916,"symbol":"dyld4::JustInTimeLoader::runInitializers(dyld4::RuntimeState&) const","symbolLocation":36,"imageIndex":6},{"imageOffset":119900,"symbol":"dyld4::Loader::runInitializersBottomUp(dyld4::RuntimeState&, dyld3::Array<dyld4::Loader const*>&) const","symbolLocation":220,"imageIndex":6},{"imageOffset":119808,"symbol":"dyld4::Loader::runInitializersBottomUp(dyld4::RuntimeState&, dyld3::Array<dyld4::Loader const*>&) const","symbolLocation":128,"imageIndex":6},{"imageOffset":119808,"symbol":"dyld4::Loader::runInitializersBottomUp(dyld4::RuntimeState&, dyld3::Array<dyld4::Loader const*>&) const","symbolLocation":128,"imageIndex":6},{"imageOffset":135404,"symbol":"dyld4::Loader::runInitializersBottomUpPlusUpwardLinks(dyld4::RuntimeState&) const::$_1::operator()() const","symbolLocation":116,"imageIndex":6},{"imageOffset":120360,"symbol":"dyld4::Loader::runInitializersBottomUpPlusUpwardLinks(dyld4::RuntimeState&) const","symbolLocation":380,"imageIndex":6},{"imageOffset":263384,"symbol":"dyld4::APIs::runAllInitializersForMain()","symbolLocation":464,"imageIndex":6},{"imageOffset":28540,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":3156,"imageIndex":6},{"imageOffset":24284,"symbol":"start","symbolLocation":1844,"imageIndex":6}]},{"id":6405639,"frames":[{"imageOffset":7456,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":8}],"threadState":{"x":[{"value":6160330752},{"value":4355},{"value":6159794176},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":4096},"fp":{"value":0},"sp":{"value":6160330752},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6673603872},"far":{"value":0}}},{"id":6405640,"frames":[{"imageOffset":7456,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":8}],"threadState":{"x":[{"value":6160904192},{"value":5379},{"value":6160367616},{"value":0},{"value":409604},{"value":18446744073709551615},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":0},"cpsr":{"value":4096},"fp":{"value":0},"sp":{"value":6160904192},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6673603872},"far":{"value":0}}}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4319838208,
    "CFBundleShortVersionString" : "1.0",
    "CFBundleIdentifier" : "com.diephouse.matt.MMMarkdown",
    "size" : 81920,
    "uuid" : "e26fee4b-77d3-3471-a034-5efd3d03c8bc",
    "path" : "\/Applications\/Surge.app\/Contents\/Frameworks\/MMMarkdown.framework\/Versions\/A\/MMMarkdown",
    "name" : "MMMarkdown",
    "CFBundleVersion" : "1"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4321558528,
    "CFBundleShortVersionString" : "6.27.0",
    "CFBundleIdentifier" : "com.bugsnag.Bugsnag",
    "size" : 294912,
    "uuid" : "9eae454d-8523-3b48-8db3-b58352906945",
    "path" : "\/Applications\/Surge.app\/Contents\/Frameworks\/Bugsnag.framework\/Versions\/A\/Bugsnag",
    "name" : "Bugsnag",
    "CFBundleVersion" : "1"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4322328576,
    "CFBundleShortVersionString" : "1.23.0",
    "CFBundleIdentifier" : "org.sparkle-project.Sparkle",
    "size" : 278528,
    "uuid" : "ec5a5170-5391-3737-94af-65386955f8df",
    "path" : "\/Applications\/Surge.app\/Contents\/Frameworks\/Sparkle.framework\/Versions\/A\/Sparkle",
    "name" : "Sparkle",
    "CFBundleVersion" : "1.23.0"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4326506496,
    "size" : 1425408,
    "uuid" : "5aeeb666-e60e-37a8-b694-cbfd92d6d759",
    "path" : "\/Applications\/Surge.app\/Contents\/Frameworks\/91QiuChenly.dylib",
    "name" : "91QiuChenly.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4307107840,
    "CFBundleShortVersionString" : "5.7.3",
    "CFBundleIdentifier" : "com.nssurge.surge-mac",
    "size" : 6569984,
    "uuid" : "04657493-b744-3c86-8ef4-e0c66701a38c",
    "path" : "\/Applications\/Surge.app\/Contents\/MacOS\/Surge",
    "name" : "Surge",
    "CFBundleVersion" : "2785"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6669565952,
    "size" : 327044,
    "uuid" : "b326b2c3-1069-3d17-b49d-9dcb24efec6f",
    "path" : "\/usr\/lib\/libobjc.A.dylib",
    "name" : "libobjc.A.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6669893632,
    "size" : 559640,
    "uuid" : "37bbc384-0755-31c7-a808-0ed49e44dd8e",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6673596416,
    "size" : 53248,
    "uuid" : "386b0fc1-7873-3328-8e71-43269fd1b2c7",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  }
],
  "sharedCache" : {
  "base" : 6669139968,
  "size" : 4220698624,
  "uuid" : "3406ad1b-2469-30eb-9863-5dce861e6dea"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.0G resident=0K(0%) swapped_out_or_unallocated=1.0G(100%)\nWritable regions: Total=843.7M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=843.7M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nActivity Tracing                   256K        1 \nKernel Alloc Once                   32K        1 \nMALLOC                           830.2M       24 \nMALLOC guard page                   96K        6 \nSTACK GUARD                       56.0M        3 \nStack                             9264K        3 \nVM_ALLOCATE                         16K        1 \n__AUTH                            1167K      251 \n__AUTH_CONST                      22.6M      433 \n__CTF                               824        1 \n__DATA                            9186K      424 \n__DATA_CONST                      22.4M      443 \n__DATA_DIRTY                      1280K      146 \n__FONT_DATA                          4K        1 \n__LINKEDIT                       533.9M        6 \n__OBJC_RO                         71.9M        1 \n__OBJC_RW                         2199K        1 \n__TEXT                           518.4M      469 \ndyld private memory               4384K        4 \nmapped file                       31.1M        2 \nshared memory                       64K        4 \n===========                     =======  ======= \nTOTAL                              2.1G     2225 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "queue" : "com.apple.main-thread"
  }
},
  "logWritingSignature" : "8d6262fdccdea15a69a7ad97c3c91dae09b16f37",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "654439cdafbf5b61207873a9",
      "factorPackIds" : {

      },
      "deploymentId" : 240000004
    },
    {
      "rolloutId" : "6425c75e4327780c10cc4252",
      "factorPackIds" : {
        "SIRI_HOME_AUTOMATION_INTENT_SELECTION_CACHE" : "642600a457e7664b1698eb32"
      },
      "deploymentId" : 240000004
    }
  ],
  "experiments" : [

  ]
}
}

**Comment by QiuChenly** [comment]
https://t.me/qiuchenlymac/365

仓库不支持注入。那选项只是给我自己用的
