### ISSUE TITLE
setapp 登录异常

### ISSUE THREAD

**Issue by 78wee** [QiuChenly/InjectLib#33]
### 检查事项

- [X] 已确保 InjectLib 更新到最新版本
- [X] 已确保软件版本为 InjectLib 支持范围

### 描述问题

error：Your Setapp installation is broken and cannot be used properly.
Please download a new copy of Setapp and reinstall it on your Mac to resolve the problem.
Download and Install

### 最小复现

<img width="328" alt="image" src="https://github.com/user-attachments/assets/c09e9e40-17d5-4024-825a-0341c0edef4b">

### 系统情况

- [ ] SIP 开着还是关着？
- [ ] 是否为黑苹果（如果是黑苹果，请回答在下方标注为黑苹果的问题）
- [ ] 黑苹果是否amfi_getout_of_my_way开了？或者操作过amfi相关属性和amfi相关quirk？

### 系统信息

```Shell
Processor 3.7 GHz 6-Core Intel Core i5 Graphics Radeon Pro 580X 8 GB Memory 40 GB 2667 MHz DDR4 Startup disk Macintosh HD erial number C02YP03KJV40 macOS Sonoma 14.5
```

### 期望行为

可以正常使用

**Comment by QiuChenly** [comment]
注入两个app

**Comment by 78wee** [comment]
您说的是这 2 个 app吗：Setapp&SetAppAgent。 如果是我分别注入了，但问题依旧，无法正常打开。我卸载重装NN 次了。

**Comment by 78wee** [comment]
setapp是按照教程里的链接下载的。
版本号是：Setapp-86 .zip

**Comment by QiuChenly** [comment]
我知道，你要注入两个Setapp,一个是SetappAgent还有一个是本体。

**Comment by 78wee** [comment]
我现在是注入成功了。但是用一键登录，无法登录您的账号啊，一直出现下图提示
<img width="328" alt="image" src="https://github.com/user-attachments/assets/d6a5fe74-6dd6-4df1-a1ee-de83e108bcf8">
<img width="301" alt="image" src="https://github.com/user-attachments/assets/b314dd10-8fea-494d-8324-14eff16c54ae">

**Comment by QiuChenly** [comment]
卸载 你只能登录我的 还有就是 你没注入成功 否则不会出现这种问题

**Comment by 78wee** [comment]
谢大佬，get done！

**Comment by zhichucode** [comment]
> 谢大佬，get done！

请问怎么解决的

**Comment by 78wee** [comment]
先打开injectgui注入一次，发现无法成功打开后，点击「原神启动」再来一次！哇，世间的爱与美好，神奇出现了。我朋友她也用了这方法，屡试不爽 ing...🤣

**Comment by QiuChenly** [comment]
> 先打开injectgui注入一次，发现无法成功打开后，点击「原神启动」再来一次！哇，世间的爱与美好，神奇出现了。我朋友她也用了这方法，屡试不爽 ing...🤣

你是懂描述的
