### ISSUE TITLE
setapp内部的软件无法注入，权限不足

### ISSUE THREAD

**Issue by zhichucode** [QiuChenly/InjectLib#39]
### 检查事项

- [X] 已确保 InjectLib 更新到最新版本
- [X] 已确保软件版本为 InjectLib 支持范围

### 描述问题

setapp 和 setapp client已经提示注入成功，并且成功登录，但是内部软件无法成功注入，提示权限不足。
<img width="806" alt="image" src="https://github.com/user-attachments/assets/bf6422aa-0896-40cf-90e5-5c70e3149a1f">

### 最小复现

使用git clone下载injectlib文件夹，然后使用python3 进行注入，首先注入setapp和setapp client，并进行成功登录。可以下载很多软件，但在注入这些软件的时候出现权限不足的情况，无法成功注入setapp里面的软件。

### 系统情况

- [ ] SIP 开着还是关着？
- [ ] 是否为黑苹果（如果是黑苹果，请回答在下方标注为黑苹果的问题）
- [ ] 黑苹果是否amfi_getout_of_my_way开了？或者操作过amfi相关属性和amfi相关quirk？

### 系统信息

```Shell
macOS 13.6
16GB
M1 pro
```

### 期望行为

期待能够成功注入setapp 中的软件

**Comment by zhichucode** [comment]
<img width="806" alt="image" src="https://github.com/user-attachments/assets/a6e29a5b-c513-4c4c-b4c3-f3ec92f1a1b2">

**Comment by QiuChenly** [comment]
你自己系统弹窗要求权限没点啊

设置 - App 管理自己找终端打开。

**Comment by zhichucode** [comment]
怎么打开这个权限呢，并没有找到这个权限

**Comment by zhichucode** [comment]
![image](https://github.com/user-attachments/assets/a51a3775-4536-48e3-a8a3-940730c0ed06)
找到了这个
