### ISSUE TITLE
table-plus not work

### ISSUE THREAD

**Issue by ijry** [QiuChenly/InjectLib#4]
### 检查事项

- [X] 已确保 InjectLib 更新到最新版本
- [X] 已确保软件版本为 InjectLib 支持范围

### 描述问题

测试发现脚本运行后table-plus6.0.8 (562)打开报错

### 最小复现

打开上述软件直接弹窗崩溃了

### 系统情况

- [ ] SIP 是否启动
- [ ] 是否为黑苹果（如果是黑苹果，请回答在下方标注了黑苹果的问题）

### 系统信息

```Shell
OS: macOS14.5
CPU: Apple M1
RAM: 8GB
```

### 期望行为

table-plus正常打开

### Crash Log

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               TablePlus [7116]
Path:                  /Applications/TablePlus.app/Contents/MacOS/TablePlus
Identifier:            com.tinyapp.TablePlus
Version:               6.0.8 (562)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-06-27 12:29:10.0108 +0800
OS Version:            macOS 14.5 (23F79)
Report Version:        12
Anonymous UUID:        BFEFCE5F-9155-89E3-9137-5AD047D1A8EB

Sleep/Wake UUID:       1FD6A3AF-9252-44C8-BA8A-5DF96F9225A6

Time Awake Since Boot: 490000 seconds
Time Since Wake:       9294 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: @rpath/SSH.framework/Versions/A/SSH
Referenced from: <B65BA7C8-857E-355B-91F5-106A82A6D051> /Applications/TablePlus.app/Contents/MacOS/TablePlus
Reason: tried: '/usr/lib/swift/SSH.framework/Versions/A/SSH' (no such file, not in dyld cache), '/System/Volumes/Preboot/Cryptexes/OS/usr/lib/swift/SSH.framework/Versions/A/SSH' (no such file), '/Applications/TablePlus.app/Contents/Frameworks/SSH.framework/Versions/A/SSH' (code signature in <09B37163-B556-33B2-BB6F-8297EDED4A67> '/Applications/TablePlus.app/Contents/Frameworks/SSH.framework/Versions/A/SSH' not valid for use in process: mapping process and mapped file (non-platform) have different Team IDs), '/Applications/TablePlus.app/Contents/MacOS/Frameworks/SSH.framework/Versions/A/SSH' (no such file), '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/SSH.framework/Versions/A/SSH' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Xcode.app/Contents/Developer/Toolchains/Xc
(terminated at launch; ignore backtrace)

Thread 0 Crashed:
0   dyld                          	       0x183969a50 __abort_with_payload + 8
1   dyld                          	       0x183974628 abort_with_payload_wrapper_internal + 104
2   dyld                          	       0x18397465c abort_with_payload + 16
3   dyld                          	       0x1839066b0 dyld4::halt(char const*, dyld4::StructuredError const*) + 304
4   dyld                          	       0x183903258 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 3888
5   dyld                          	       0x183901edc start + 1844

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000006   x1: 0x0000000000000001   x2: 0x000000016d1668a0   x3: 0x000000000000006d
    x4: 0x000000016d1664a0   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000000000000000
    x8: 0x0000000000000020   x9: 0x000000016d16640d  x10: 0x000000000000000a  x11: 0x0000000000000000
   x12: 0x0000000000000037  x13: 0x1000000000000000  x14: 0x0000000000000004  x15: 0x0000000000008000
   x16: 0x0000000000000209  x17: 0x00000001838ff37c  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x000000016d1664a0  x21: 0x000000000000006d  x22: 0x000000016d1668a0  x23: 0x0000000000000001
   x24: 0x0000000000000006  x25: 0x0000000000000001  x26: 0x000000016d167288  x27: 0x0000000000000101
   x28: 0x000000016d167348   fp: 0x000000016d166470   lr: 0x0000000183974628
    sp: 0x000000016d166430   pc: 0x0000000183969a50 cpsr: 0x80001000
   far: 0x0000000000000000  esr: 0x56000080  Address size fault

Binary Images:
       0x103b34000 -        0x103b77fff org.sparkle-project.Sparkle (2.6.2) <9e381d0d-f577-304a-ad0c-8e365d54adf0> /Applications/TablePlus.app/Contents/Frameworks/Sparkle.framework/Versions/B/Sparkle
       0x103f3c000 -        0x104073fff com.tableplus.Redis (1.0) <f15e8507-5d6e-3295-b9c2-4394292a78c0> /Applications/TablePlus.app/Contents/Frameworks/Redis.framework/Versions/A/Redis
       0x103b9c000 -        0x103e1bfff com.tableplus.PostgreSQL (1.0) <7f2bd7ad-4b67-353e-9420-22b4e3c08134> /Applications/TablePlus.app/Contents/Frameworks/PostgreSQL.framework/Versions/A/PostgreSQL
       0x104328000 -        0x1043dffff com.tableplus.SQL (1.0) <8bb05c4d-9851-389e-a6b1-85574c86093a> /Applications/TablePlus.app/Contents/Frameworks/SQL.framework/Versions/A/SQL
       0x103a60000 -        0x103ad3fff - (1.0) <66ebbf71-fcea-35ce-bc69-b0df37720f62> /Applications/TablePlus.app/Contents/Frameworks/LibSQL.framework/Versions/A/LibSQL
       0x104100000 -        0x10420ffff - (1.0) <c0a407ff-8462-3671-adb6-cd2efae1c78e> /Applications/TablePlus.app/Contents/Frameworks/BigQuery.framework/Versions/A/BigQuery
       0x1057e4000 -        0x105d8ffff - (1.0) <12d74127-3ca8-3d39-9fcd-475041d2629e> /Applications/TablePlus.app/Contents/Frameworks/MySQL.framework/Versions/A/MySQL
       0x104b18000 -        0x104d53fff com.tableplus.ClickHouse (1.0) <079dc7d6-9a2f-3a93-9b23-63de7dbc9c30> /Applications/TablePlus.app/Contents/Frameworks/ClickHouse.framework/Versions/A/ClickHouse
       0x1045a8000 -        0x10461ffff - (1.0) <3ae28956-f734-3deb-ae4e-1d038b79b45f> /Applications/TablePlus.app/Contents/Frameworks/CloudflareD1.framework/Versions/A/CloudflareD1
       0x104664000 -        0x10487bfff com.tableplus.Snowflake (1.0) <bd3966c5-fec9-3a8a-bbb4-186fb4e4146d> /Applications/TablePlus.app/Contents/Frameworks/Snowflake.framework/Versions/A/Snowflake
       0x10b758000 -        0x10d147fff com.tableplus.DuDB (1.0) <9f1d1a8d-c288-3cf4-92bf-72a864a6d4aa> /Applications/TablePlus.app/Contents/Frameworks/DuDB.framework/Versions/A/DuDB
       0x105450000 -        0x105663fff com.tableplus.MicrosoftSQLServer (1.0) <59e289d8-2f8b-3718-8afc-616c8dacc4a5> /Applications/TablePlus.app/Contents/Frameworks/MicrosoftSQLServer.framework/Versions/A/MicrosoftSQLServer
       0x104e6c000 -        0x1051a3fff com.tableplus.Cassandra (1.0) <6413d859-1ae0-3399-87e4-bdc07fd74217> /Applications/TablePlus.app/Contents/Frameworks/Cassandra.framework/Versions/A/Cassandra
       0x102c98000 -        0x10342ffff com.tinyapp.TablePlus (6.0.8) <b65ba7c8-857e-355b-91f5-106a82a6d051> /Applications/TablePlus.app/Contents/MacOS/TablePlus
       0x1838fc000 -        0x183984a17 dyld (*) <37bbc384-0755-31c7-a808-0ed49e44dd8e> /usr/lib/dyld
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 6
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=611.6M resident=0K(0%) swapped_out_or_unallocated=611.6M(100%)
Writable regions: Total=12.7M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=12.7M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8176K        1 
VM_ALLOCATE                         16K        1 
__DATA                            4907K       28 
__DATA_CONST                      2455K       15 
__DATA_DIRTY                         7K        1 
__LINKEDIT                       555.6M       15 
__TEXT                            56.1M       15 
dyld private memory               4384K        4 
===========                     =======  ======= 
TOTAL                            687.1M       81 

-----------
Full Report
-----------

{"app_name":"TablePlus","timestamp":"2024-06-27 12:29:10.00 +0800","app_version":"6.0.8","slice_uuid":"b65ba7c8-857e-355b-91f5-106a82a6d051","build_version":"562","platform":1,"bundleID":"com.tinyapp.TablePlus","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 14.5 (23F79)","roots_installed":0,"name":"TablePlus","incident_id":"23785D88-7284-4FD4-9162-1FFD3DAB8514"}
{
  "uptime" : 490000,
  "procRole" : "Default",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookAir10,1",
  "coalitionID" : 117545,
  "osVersion" : {
    "train" : "macOS 14.5",
    "build" : "23F79",
    "releaseType" : "User"
  },
  "captureTime" : "2024-06-27 12:29:10.0108 +0800",
  "codeSigningMonitor" : 1,
  "incident" : "23785D88-7284-4FD4-9162-1FFD3DAB8514",
  "pid" : 7116,
  "translated" : false,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2024-06-27 12:29:09.9871 +0800",
  "procStartAbsTime" : 11914721957697,
  "procExitAbsTime" : 11914722497534,
  "procName" : "TablePlus",
  "procPath" : "\/Applications\/TablePlus.app\/Contents\/MacOS\/TablePlus",
  "bundleInfo" : {"CFBundleShortVersionString":"6.0.8","CFBundleVersion":"562","CFBundleIdentifier":"com.tinyapp.TablePlus"},
  "storeInfo" : {"deviceIdentifierForVendor":"39A40C29-CD11-5878-8441-089B7149B7AA","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.tinyapp.TablePlus",
  "crashReporterKey" : "BFEFCE5F-9155-89E3-9137-5AD047D1A8EB",
  "codeSigningID" : "com.tinyapp.TablePlus",
  "codeSigningTeamID" : "3X57WP8E8V",
  "codeSigningFlags" : 570499601,
  "codeSigningValidationCategory" : 6,
  "codeSigningTrustLevel" : 4294967295,
  "instructionByteStream" : {"beforePC":"1AAAABABAAAYAQAAIAEAACgBAAAwAQAAOAEAAFQBAAAwQYDSARAA1A==","atPC":"AwEAVH8jA9X9e7+p\/QMAkQpV\/pe\/AwCR\/XvBqP8PX9bAA1\/WEC2A0g=="},
  "wakeTime" : 9294,
  "sleepWakeUUID" : "1FD6A3AF-9252-44C8-BA8A-5DF96F9225A6",
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":1,"flags":518,"namespace":"DYLD","indicator":"Library missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Library not loaded: @rpath\/SSH.framework\/Versions\/A\/SSH","Referenced from: <B65BA7C8-857E-355B-91F5-106A82A6D051> \/Applications\/TablePlus.app\/Contents\/MacOS\/TablePlus","Reason: tried: '\/usr\/lib\/swift\/SSH.framework\/Versions\/A\/SSH' (no such file, not in dyld cache), '\/System\/Volumes\/Preboot\/Cryptexes\/OS\/usr\/lib\/swift\/SSH.framework\/Versions\/A\/SSH' (no such file), '\/Applications\/TablePlus.app\/Contents\/Frameworks\/SSH.framework\/Versions\/A\/SSH' (code signature in <09B37163-B556-33B2-BB6F-8297EDED4A67> '\/Applications\/TablePlus.app\/Contents\/Frameworks\/SSH.framework\/Versions\/A\/SSH' not valid for use in process: mapping process and mapped file (non-platform) have different Team IDs), '\/Applications\/TablePlus.app\/Contents\/MacOS\/Frameworks\/SSH.framework\/Versions\/A\/SSH' (no such file), '\/Applications\/Xcode.app\/Contents\/Developer\/Toolchains\/XcodeDefault.xctoolchain\/usr\/lib\/swift\/macosx\/SSH.framework\/Versions\/A\/SSH' (no such file), '\/System\/Volumes\/Preboot\/Cryptexes\/OS\/Applications\/Xcode.app\/Contents\/Developer\/Toolchains\/Xc"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":6},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":9648185,"threadState":{"x":[{"value":6},{"value":1},{"value":6125152416},{"value":109},{"value":6125151392},{"value":0},{"value":0},{"value":0},{"value":32},{"value":6125151245},{"value":10},{"value":0},{"value":55},{"value":1152921504606846976},{"value":4},{"value":32768},{"value":521},{"value":6502216572,"symbolLocation":416,"symbol":"__simple_bprintf"},{"value":0},{"value":0},{"value":6125151392},{"value":109},{"value":6125152416},{"value":1},{"value":6},{"value":1},{"value":6125154952},{"value":257},{"value":6125155144}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6502696488},"cpsr":{"value":2147487744},"fp":{"value":6125151344},"sp":{"value":6125151280},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":6502652496,"matchesCrashFrame":1},"far":{"value":0}},"frames":[{"imageOffset":449104,"symbol":"__abort_with_payload","symbolLocation":8,"imageIndex":14},{"imageOffset":493096,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":104,"imageIndex":14},{"imageOffset":493148,"symbol":"abort_with_payload","symbolLocation":16,"imageIndex":14},{"imageOffset":42672,"symbol":"dyld4::halt(char const*, dyld4::StructuredError const*)","symbolLocation":304,"imageIndex":14},{"imageOffset":29272,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":3888,"imageIndex":14},{"imageOffset":24284,"symbol":"start","symbolLocation":1844,"imageIndex":14}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4357046272,
    "CFBundleShortVersionString" : "2.6.2",
    "CFBundleIdentifier" : "org.sparkle-project.Sparkle",
    "size" : 278528,
    "uuid" : "9e381d0d-f577-304a-ad0c-8e365d54adf0",
    "path" : "\/Applications\/TablePlus.app\/Contents\/Frameworks\/Sparkle.framework\/Versions\/B\/Sparkle",
    "name" : "Sparkle",
    "CFBundleVersion" : "2038"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4361273344,
    "CFBundleShortVersionString" : "1.0",
    "CFBundleIdentifier" : "com.tableplus.Redis",
    "size" : 1277952,
    "uuid" : "f15e8507-5d6e-3295-b9c2-4394292a78c0",
    "path" : "\/Applications\/TablePlus.app\/Contents\/Frameworks\/Redis.framework\/Versions\/A\/Redis",
    "name" : "Redis",
    "CFBundleVersion" : "1"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4357472256,
    "CFBundleShortVersionString" : "1.0",
    "CFBundleIdentifier" : "com.tableplus.PostgreSQL",
    "size" : 2621440,
    "uuid" : "7f2bd7ad-4b67-353e-9420-22b4e3c08134",
    "path" : "\/Applications\/TablePlus.app\/Contents\/Frameworks\/PostgreSQL.framework\/Versions\/A\/PostgreSQL",
    "name" : "PostgreSQL",
    "CFBundleVersion" : "1"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4365385728,
    "CFBundleShortVersionString" : "1.0",
    "CFBundleIdentifier" : "com.tableplus.SQL",
    "size" : 753664,
    "uuid" : "8bb05c4d-9851-389e-a6b1-85574c86093a",
    "path" : "\/Applications\/TablePlus.app\/Contents\/Frameworks\/SQL.framework\/Versions\/A\/SQL",
    "name" : "SQL",
    "CFBundleVersion" : "1"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4356177920,
    "CFBundleShortVersionString" : "1.0",
    "CFBundleIdentifier" : "-",
    "size" : 475136,
    "uuid" : "66ebbf71-fcea-35ce-bc69-b0df37720f62",
    "path" : "\/Applications\/TablePlus.app\/Contents\/Frameworks\/LibSQL.framework\/Versions\/A\/LibSQL",
    "name" : "LibSQL",
    "CFBundleVersion" : "1"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4363124736,
    "CFBundleShortVersionString" : "1.0",
    "CFBundleIdentifier" : "-",
    "size" : 1114112,
    "uuid" : "c0a407ff-8462-3671-adb6-cd2efae1c78e",
    "path" : "\/Applications\/TablePlus.app\/Contents\/Frameworks\/BigQuery.framework\/Versions\/A\/BigQuery",
    "name" : "BigQuery",
    "CFBundleVersion" : "1"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4387127296,
    "CFBundleShortVersionString" : "1.0",
    "CFBundleIdentifier" : "-",
    "size" : 5947392,
    "uuid" : "12d74127-3ca8-3d39-9fcd-475041d2629e",
    "path" : "\/Applications\/TablePlus.app\/Contents\/Frameworks\/MySQL.framework\/Versions\/A\/MySQL",
    "name" : "MySQL",
    "CFBundleVersion" : "1"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4373708800,
    "CFBundleShortVersionString" : "1.0",
    "CFBundleIdentifier" : "com.tableplus.ClickHouse",
    "size" : 2342912,
    "uuid" : "079dc7d6-9a2f-3a93-9b23-63de7dbc9c30",
    "path" : "\/Applications\/TablePlus.app\/Contents\/Frameworks\/ClickHouse.framework\/Versions\/A\/ClickHouse",
    "name" : "ClickHouse",
    "CFBundleVersion" : "1"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4368007168,
    "CFBundleShortVersionString" : "1.0",
    "CFBundleIdentifier" : "-",
    "size" : 491520,
    "uuid" : "3ae28956-f734-3deb-ae4e-1d038b79b45f",
    "path" : "\/Applications\/TablePlus.app\/Contents\/Frameworks\/CloudflareD1.framework\/Versions\/A\/CloudflareD1",
    "name" : "CloudflareD1",
    "CFBundleVersion" : "1"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4368777216,
    "CFBundleShortVersionString" : "1.0",
    "CFBundleIdentifier" : "com.tableplus.Snowflake",
    "size" : 2195456,
    "uuid" : "bd3966c5-fec9-3a8a-bbb4-186fb4e4146d",
    "path" : "\/Applications\/TablePlus.app\/Contents\/Frameworks\/Snowflake.framework\/Versions\/A\/Snowflake",
    "name" : "Snowflake",
    "CFBundleVersion" : "1"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4487217152,
    "CFBundleShortVersionString" : "1.0",
    "CFBundleIdentifier" : "com.tableplus.DuDB",
    "size" : 27197440,
    "uuid" : "9f1d1a8d-c288-3cf4-92bf-72a864a6d4aa",
    "path" : "\/Applications\/TablePlus.app\/Contents\/Frameworks\/DuDB.framework\/Versions\/A\/DuDB",
    "name" : "DuDB",
    "CFBundleVersion" : "1"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4383375360,
    "CFBundleShortVersionString" : "1.0",
    "CFBundleIdentifier" : "com.tableplus.MicrosoftSQLServer",
    "size" : 2179072,
    "uuid" : "59e289d8-2f8b-3718-8afc-616c8dacc4a5",
    "path" : "\/Applications\/TablePlus.app\/Contents\/Frameworks\/MicrosoftSQLServer.framework\/Versions\/A\/MicrosoftSQLServer",
    "name" : "MicrosoftSQLServer",
    "CFBundleVersion" : "1"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4377198592,
    "CFBundleShortVersionString" : "1.0",
    "CFBundleIdentifier" : "com.tableplus.Cassandra",
    "size" : 3375104,
    "uuid" : "6413d859-1ae0-3399-87e4-bdc07fd74217",
    "path" : "\/Applications\/TablePlus.app\/Contents\/Frameworks\/Cassandra.framework\/Versions\/A\/Cassandra",
    "name" : "Cassandra",
    "CFBundleVersion" : "1"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4341727232,
    "CFBundleShortVersionString" : "6.0.8",
    "CFBundleIdentifier" : "com.tinyapp.TablePlus",
    "size" : 7962624,
    "uuid" : "b65ba7c8-857e-355b-91f5-106a82a6d051",
    "path" : "\/Applications\/TablePlus.app\/Contents\/MacOS\/TablePlus",
    "name" : "TablePlus",
    "CFBundleVersion" : "562"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6502203392,
    "size" : 559640,
    "uuid" : "37bbc384-0755-31c7-a808-0ed49e44dd8e",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  }
],
  "sharedCache" : {
  "base" : 6501449728,
  "size" : 4220698624,
  "uuid" : "3406ad1b-2469-30eb-9863-5dce861e6dea"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=611.6M resident=0K(0%) swapped_out_or_unallocated=611.6M(100%)\nWritable regions: Total=12.7M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=12.7M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8176K        1 \nVM_ALLOCATE                         16K        1 \n__DATA                            4907K       28 \n__DATA_CONST                      2455K       15 \n__DATA_DIRTY                         7K        1 \n__LINKEDIT                       555.6M       15 \n__TEXT                            56.1M       15 \ndyld private memory               4384K        4 \n===========                     =======  ======= \nTOTAL                            687.1M       81 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "logWritingSignature" : "1d1f4f797334a28ff518b684dec4f335345fb770",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "60356660bbe37970735c5624",
      "factorPackIds" : {

      },
      "deploymentId" : 240000027
    },
    {
      "rolloutId" : "632c763c58740028737bfdd2",
      "factorPackIds" : {
        "SIRI_DIALOG_ASSETS" : "64a57d23fa6fd41b2353e2ae"
      },
      "deploymentId" : 240000034
    }
  ],
  "experiments" : [

  ]
}
}

Model: MacBookAir10,1, BootROM 10151.121.1, proc 8:4:4 processors, 8 GB, SMC 
Graphics: Apple M1, Apple M1, Built-In
Display: Color LCD, 2560 x 1600 Retina, Main, MirrorOff, Online
Memory Module: LPDDR4, Micron
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4378), wl0: Jan 13 2024 03:06:59 version 18.20.440.9.7.8.167 FWID 01-7be24857
AirPort: 
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB31Bus
Thunderbolt Bus: MacBook Air, Apple Inc.
Thunderbolt Bus: MacBook Air, Apple Inc.

**Comment by QiuChenly** [comment]
看着像缺少了文件，不清楚你是怎么搞的，一般来说直接注入是没有问题的。

**Comment by ijry** [comment]
就点击链接下载安装tableplus，然后启动脚本注入。claenmymac可以，这个就不行。

**Comment by QiuChenly** [comment]
日志我看了，跟签名有关系。暂时不清楚是怎么触发的，有时间我让其他人跟进一下这个问题。

**Comment by ijry** [comment]
<img width="849" alt="image" src="https://github.com/QiuChenly/InjectLib/assets/3102798/140a3377-8d9e-4458-851e-7592b485bbd6">
这个不知道能不能有帮助

**Comment by jeasonnow** [comment]
![CleanShot 2024-07-19 at 10 42 07@2x](https://github.com/user-attachments/assets/9b2f0347-508b-45ba-9838-c81a2353e1e2)

@ijry 用最新的代码试试，我感觉你这个没有 --deep 控制哦。

**Comment by ijry** [comment]
> ![CleanShot 2024-07-19 at 10 42 07@2x](https://private-user-images.githubusercontent.com/16950207/350207538-9b2f0347-508b-45ba-9838-c81a2353e1e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNTc5ODUsIm5iZiI6MTcyMTM1NzY4NSwicGF0aCI6Ii8xNjk1MDIwNy8zNTAyMDc1MzgtOWIyZjAzNDctNTA4Yi00NWJhLTk4MzgtYzgxYTIzNTNlMWUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDAyNTQ0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxMGRmMTg2ZTQ2ZjdlYmY3MzQ0MDBjYzdkMWRlNTUzOGRjYjU3ZWRjNTJkYzFjOTMxNjE4ZTk2MWQzZWMwMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2N801BFoIHILcux2uLAnEgJmldLRKUJWQOlTIsL9zPY)
> 
> @ijry 用最新的代码试试，我感觉你这个没有 --deep 控制哦。

--deep控制是啥

**Comment by ijry** [comment]
it worked now, thks.
