### ISSUE TITLE
MarginNote 4 4.1.4注入后闪退

### ISSUE THREAD

**Issue by shoudeyunkaijianyueming** [QiuChenly/InjectLib#41]
### 检查事项

- [X] 已确保 InjectLib 更新到最新版本
- [X] 已确保软件版本为 InjectLib 支持范围

### 描述问题

MarginNote 4 4.1.4注入后闪退，重签名或者绕过签名都不行

注入后闪退

### 最小复现

上个版本闪退，大佬修复好了，但这个版本也闪退，麻烦大佬了

### 系统情况

- [ ] SIP 开着还是关着？
- [ ] 是否为黑苹果（如果是黑苹果，请回答在下方标注为黑苹果的问题）
- [ ] 黑苹果是否amfi_getout_of_my_way开了？或者操作过amfi相关属性和amfi相关quirk？

### 系统信息

```Shell
OS：macos12.6.7
CPU:intel
Memory:16g
```

### 是否修改了nvram的内核启动参数（黑苹果）

无

### 是否使用了需要修改系统文件的工具（黑苹果）

无

### 期望行为

修复闪退

### 额外信息

无

### Crash Log

更上次感觉差不多

**Comment by X1a0He** [comment]
该问题已被修复，等待更新即可

**Comment by shoudeyunkaijianyueming** [comment]
老哥，我看脚本是不是更新了，但还是闪退呀

**Comment by getonefr33** [comment]
MarginNote 4 最新版本是 4.1.6，注入后仍然崩溃。其实崩溃从 4.1.4 开始就存在了
