### ISSUE TITLE
Navicat Premium17启动失败，提示：exit(173)不可用

### ISSUE THREAD

**Issue by somelou** [QiuChenly/InjectLib#44]
### 检查事项

- [X] 已确保 InjectLib 更新到最新版本
- [X] 已确保软件版本为 InjectLib 支持范围

### 描述问题

在 MacOS macOS Sequoia15, Apple M3 Pro 上激活 Navicat Premium(17.1.2)，注入成功，但是启动应用后提示：
exit(173)不可用
exit(173) API不再可用。你可以改用Transaction.all 或 AppTransaction.shared来验证App内购买。
<img width="260" alt="image" src="https://github.com/user-attachments/assets/7c423b38-3eef-4868-9f82-441e2b98fd80">
再上述弹窗点击「好」后，提示应用已损坏的弹窗：
![image](https://github.com/user-attachments/assets/b4b9f6f3-a706-423c-8767-2fda8804b2cb)

### 最小复现

1. 商店下载Navicat Premium(17.1.2)
2. 切换到 InjectLib 目录下，执行 python3 main.py，navicat premium执行y，并等待执行结束
3. 点击Navicat Premium打开，等待几秒后出现上述错误弹窗

### 系统情况

- [X] SIP 开着还是关着？
- [ ] 是否为黑苹果（如果是黑苹果，请回答在下方标注为黑苹果的问题）
- [ ] 黑苹果是否amfi_getout_of_my_way开了？或者操作过amfi相关属性和amfi相关quirk？

### 系统信息

```Shell
OS: MacOS Sequoia 15.0
CPU: Apple M3 Pro
Memory：36G
```

### 期望行为

navigate premium17能够正常注入并打开使用

### 额外信息

1. 使用App Cleaner & Uninstaller卸载重装后重试无效

**Comment by QiuChenly** [comment]
![image](https://github.com/user-attachments/assets/a8a46809-b74d-43f4-9c2f-48277866d4ca)
本地测试没有问题，稍后会提交新的Patch上去，你可以pull下来再注入看看是否还正常哦

**Comment by somelou** [comment]
pull了之后重试还是一样的错误提示
<img width="650" alt="image" src="https://github.com/user-attachments/assets/2d2b4814-dc41-44a5-81e1-def2f78a7150">

**Comment by QiuChenly** [comment]
> pull了之后重试还是一样的错误提示 <img alt="image" width="641" src="https://private-user-images.githubusercontent.com/27142016/374492566-a2f9cae9-da4c-4036-a623-16586ecb05af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0OTM1MzIsIm5iZiI6MTcyODQ5MzIzMiwicGF0aCI6Ii8yNzE0MjAxNi8zNzQ0OTI1NjYtYTJmOWNhZTktZGE0Yy00MDM2LWE2MjMtMTY1ODZlY2IwNWFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDE3MDAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3ZmFjMTE3ZDAwNDk0Mzk5MjJhM2RmYWJjNWFlZTIzOGYwNGUxMjJlODQ3YzJmMmFkZTU5YzAzMzczNDNiNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XZ8EDqEmQo966KtgdCSiMQZ8RugzGwXTn-5Xrby27lM">

进群 然后晚上六点多七点下班跟我反馈即可 应该不是什么大问题
