### ISSUE TITLE
Setapp 内部应用程序报错 1701

### ISSUE THREAD

**Issue by DavidMax2006** [QiuChenly/InjectLib#46]
### 检查事项

- [X] 已确保 InjectLib 更新到最新版本
- [X] 已确保软件版本为 InjectLib 支持范围

### 描述问题

The operation couldn’t be completed. (.error error 1701.)

### 最小复现

采用本项目网站提供的[手动下载网址](https://store.setapp.com/updates/beta.xml)下载并解压了 [`Setapp-86.zip`](https://dl.devmate.com/com.setapp.DesktopClient/86/1724077821/Setapp-86.zip)（之前尝试过最新版本 `92.0b` ，同样的问题，此次默认采用教程同步的版本），得到 `Setapp` 应用程序（288.6 MB），直接将其拖拽到系统的应用程序文件夹，未打开 `Setapp` 。

下载项目源码，运行 `秋城落叶_启动.command` ，输入明文密码后扫描应用程序文件夹，检索到 `Setapp` 并注入成功，但**并没有检索到 `SetappAgent`** （这可能是问题所在，但可以从注入输出看出已经对 `SetappAgent` 进行处理），但可以从 `Setapp` 包内容中的相应目录找到。

![CleanShot 2024-10-05 at 11 57 04@2x](https://github.com/user-attachments/assets/6b96fc68-f647-493c-97dd-f4ad4cbcb117)

![CleanShot 2024-10-05 at 11 59 11@2x](https://github.com/user-attachments/assets/ca0f1cae-7fe2-404b-9853-191995ff8a76)

运行 `Setapp` ，正确弹出相应的窗口：

![CleanShot 2024-10-05 at 12 02 56@2x](https://github.com/user-attachments/assets/824bc042-f4a4-4b72-b282-10053bbb90fc)

使用网站提供的一键登录链接，成功显示个人激活信息：

![CleanShot 2024-10-05 at 12 05 00@2x](https://github.com/user-attachments/assets/a6abdda0-0fe2-407a-a1f3-972e131fc67d)

在 `Setapp` 内部安装应用程序（以 `Bartender` 为例，实际上试了几款应用程序均出现同样的问题），打开后显示如下信息：

![CleanShot 2024-10-05 at 12 07 21@2x](https://github.com/user-attachments/assets/698369ba-9bfb-415a-bd3d-ccff422ab726)

重新运行 `秋城落叶_启动.command` 并尝试注入 `Setapp` 内部安装的应用程序，报错，无效果。

![CleanShot 2024-10-05 at 12 14 30@2x](https://github.com/user-attachments/assets/29e7341e-af96-4a67-90dd-9fd7ee03dab0)

### 系统情况

- [X] SIP 开着还是关着？
- [ ] 是否为黑苹果（如果是黑苹果，请回答在下方标注为黑苹果的问题）
- [ ] 黑苹果是否amfi_getout_of_my_way开了？或者操作过amfi相关属性和amfi相关quirk？

### 系统信息

```Shell
OS: MacOS Sequoia 15.0
Chip: Apple M3 Pro
Memory: 18GB
```

### 期望行为

正常运行 `Setapp` 内部安装的应用程序并使用。

### 额外信息

我尝试了网站提供对于[文件已损坏的解决办法](https://qiuchenlyopensource.github.io/Documentaions/file-is-damaged.html)，没有效果。

**Comment by QiuChenly** [comment]
下载后的程序依然要注入。

**Comment by NKU915** [comment]
遇到同样的问题，Setapp激活以后，再安装的app，比如：Plus，PDF Pals都是同样的error 1701错误，试图强制杀死进程：SetappAgent和SetappLauncher，结果是无法杀死。因为是两个互为守护的进程，现在要怎么处理？

**Comment by QiuChenly** [comment]
> 遇到同样的问题，Setapp激活以后，再安装的app，比如：Plus，PDF Pals都是同样的error 1701错误，试图强制杀死进程：SetappAgent和SetappLauncher，结果是无法杀死。因为是两个互为守护的进程，现在要怎么处理？

https://qiuchenlyopensource.github.io/Documentaions/setapp.html#reinject-after-updating-or-downloading
文档告诉你了要对app也要注入 我真无语

**Comment by NKU915** [comment]
不好意思啊，最终确实看到你链接中的信息成功了
