### ISSUE TITLE
ProxyMan 5.6.1 注入后“重载 macOS 代理”无法工作，

### ISSUE THREAD

**Issue by uclort** [QiuChenly/InjectLib#5]
### 检查事项

- [X] 已确保 InjectLib 更新到最新版本
- [X] 已确保软件版本为 InjectLib 支持范围

### 描述问题

尝试重复安装 Proxy Helper Tool，不能解决问题

### 最小复现

安装 ProxyMan 5.6.1，使用 “秋城落叶_启动.command” 注入

### 系统情况

- [X] SIP 是否启动
- [ ] 是否为黑苹果（如果是黑苹果，请回答在下方标注了黑苹果的问题）

### 系统信息

```Shell
intel 系列
macOS 14.5
```

### 期望行为

正常使用

**Comment by QiuChenly** [comment]
我已经关注到了此问题 请等待修复哦
