### ISSUE TITLE
setapp 中，sideNotes 软件 注入成功后，打开还是 1701

### ISSUE THREAD

**Issue by 296230428** [QiuChenly/InjectLib#51]
## Issue description

Tests found that {sideNotes} cannot be activated
{setapp 已成功，通过 setapp 下载的sideNotes,再次注入 sideNotes后，打开还是提示 1701 （The operation couldn’t be completed. (.error error 1701.)）}

## Device Information:

```
System: macOS {15.0.1}
CPU   : {Apple M3}
Memory: {16G}
SIP   : {off}
Hackintosh or Macintosh: {Macintosh}

If it is a Hackintosh, please provide more information:
Have you modified the kernel startup parameters of nvram?
Yes, I used {parameter} -v alc-layout-id={parameter}, etc.

Have you used tools such as OpenCore LegecyPatcher that require modifying system files?
Yes, I used {toolName} and turned off {...}

Is there any additional environmental information that needs to be added?
Yes, My computer is {...}
```

## Reproduction

- 前提是已经注入好setapp, 登录完成。
- {从 setapp 上下载好 sideNotes}
- enter {第一次打开 sideNotes}
- click {continue}
- click { 是否 iclued continue}
- 就弹窗 1701 (The operation couldn’t be completed. (.error error 1701.))

## Expected behavior

{正常打开}

## Actual behavior
<img width="996" alt="image" src="https://github.com/user-attachments/assets/6b98c75d-fd23-420b-bfc4-e1d0fe373746">
<img width="996" alt="image" src="https://github.com/user-attachments/assets/f3c354f6-bb10-450c-8776-2b601881c3f8">
<img width="927" alt="image" src="https://github.com/user-attachments/assets/292e45e6-853b-4474-84ff-eb02468bf634">

**Comment by QiuChenly** [comment]
Setapp中下载安装的需要用脚本注入一下这个app。

**Comment by QiuChenly** [comment]
如果脚本没找到这个app，可以自己在config.json中自己添加这个app的bundleid。

**Comment by 296230428** [comment]
噢噢，我注入了，但是注入失败了，
<img width="1098" alt="image" src="https://github.com/user-attachments/assets/1e42cff4-6ad2-4d71-aefa-1f558f370039">

**Comment by 296230428** [comment]
@QiuChenly  请问是必须关闭 SIP 吗

**Comment by QiuChenly** [comment]
设置 隐私安全 App管理 找到终端 打开就行了

**Comment by 296230428** [comment]
> Quote reply

好的，我已经关闭 SIP注入成功了，下次更新别的时再试试，感谢大佬
