### ISSUE TITLE
Powerpoint 16.90.2 打开崩溃

### ISSUE THREAD

**Issue by Lonense** [QiuChenly/InjectLib#55]
### 检查事项

- [X] 已确保 InjectLib 更新到最新版本
- [X] 已确保软件版本为 InjectLib 支持范围

### 描述问题

测试发现Powerpoint激活后打开崩溃，版本为16.90.2，但Words激活正常。

### 最小复现

从Mac app store 下载Microsoft powerpoint后，用injectlib ./秋城落叶_启动.command 激活，然后打开powerpoint直接崩溃。

### 系统情况

- [X] SIP 开着还是关着？
- [ ] 是否为黑苹果（如果是黑苹果，请回答在下方标注为黑苹果的问题）
- [ ] 黑苹果是否amfi_getout_of_my_way开了？或者操作过amfi相关属性和amfi相关quirk？

### 系统信息

```Shell
OS: MacOS 15.1
内存: 16 GB 2667 MHz DDR4
处理器: 2.6 GHz 六核Intel Core i7
```

### 期望行为

不崩溃

**Comment by QiuChenly** [comment]
需要日志。

**Comment by QiuChenly** [comment]
![image](https://github.com/user-attachments/assets/d3904e2e-76f4-4daf-8cd7-23ebdbb1c9ee)

![image](https://github.com/user-attachments/assets/1a3d0d6f-aa8a-4e16-902d-d921e218492b)

本机环境:
Intel i5 黑苹果
SIP状态：关闭
注入方法：最新仓库直接注入

自测无任何问题。
