### ISSUE TITLE
excel问题

### ISSUE THREAD

**Issue by wangyansz** [QiuChenly/InjectLib#6]
### 检查事项

- [X] 已确保 InjectLib 更新到最新版本
- [X] 已确保软件版本为 InjectLib 支持范围

### 描述问题

excel激活后，使用中关闭按键（c+w）失效，快捷键及菜单栏中的关闭都不管用，左上角红点也不行，只能退出（c+q）
word和ppt正常，只有excel不行，16.87和16.86都不行，以前用16.85版本是正常的

### 最小复现

excel激活后，使用中关闭按键（c+w）失效，快捷键及菜单栏中的关闭都不管用，左上角红点也不行，只能退出（c+q）

### 系统情况

- [ ] SIP 是否启动
- [ ] 是否为黑苹果（如果是黑苹果，请回答在下方标注了黑苹果的问题）

### 系统信息

```Shell
OS: macOS 13.6.7
CPU: Intel
Memory: 8 GB
```

### 期望行为

 能正常使用关闭按键或快捷键

### 额外信息

卸载、清理，重装、重新激活，问题仍然存在

**Comment by QiuChenly** [comment]
这是使用了通用破解导致的，该破解方式解决了所有版本通杀的问题，但是引入了几个类似于无法关闭的小问题，正在研究怎么解决。

**Comment by QiuChenly** [comment]
这个问题暂时无解，暂时不影响正常使用哦。
