### ISSUE TITLE
proxyman5.11 注入成功 实际没成功呢

### ISSUE THREAD

**Issue by Ghs0my** [QiuChenly/InjectLib#62]
### 检查事项

- [X] 已确保 InjectLib 更新到最新版本
- [X] 已确保软件版本为 InjectLib 支持范围

### 描述问题

proxyman5.11 注入成功 实际没成功呢
/Applications/Proxyman.app/Contents/Library/LaunchServices/com.proxyman.NSProxy.HelperTool 目标文件已经存在. 要重写他吗? [y/n] y
这是一个FAT格式二进制,携带 2 个架构的代码(Intel/Apple Silicon ARM64).
发现代码加载签名: LC_CODE_SIGNATURE load command. 要自动删掉吗? [y/n] y
发现代码加载签名: LC_CODE_SIGNATURE load command. 要自动删掉吗? [y/n] y
添加 LC_LOAD_DYLIB 指令到通用架构, 应用程序：/Applications/Proxyman.app/Contents/Library/LaunchServices/com.proxyman.NSProxy.HelperTool。
/Applications/Proxyman.app: replacing existing signature
App处理完成。

### 最小复现

App处理完成后 打开proxyman 发现没有升级为pro pro功能也无法使用

### 系统情况

- [ ] SIP 开着还是关着？
- [ ] 是否为黑苹果（如果是黑苹果，请回答在下方标注为黑苹果的问题）
- [ ] 黑苹果是否amfi_getout_of_my_way开了？或者操作过amfi相关属性和amfi相关quirk？

### 系统信息

```Shell
OS: macos 15.1
CPU: 2.4 GHz 八核Intel Core i9
Memory: 32 GB 2667 MHz DDR4
```

### 期望行为

成功破解

**Comment by QiuChenly** [comment]
新版本沒有做修復，稍後提交修復上來喔

**Comment by QiuChenly** [comment]
已修复，请直接下载打包好的版本。
https://t.me/qiuchenlymac/471

**Comment by SevenMrs** [comment]
> 已修复，请直接下载打包好的版本。 https://t.me/qiuchenlymac/471

需要使用项目再次破解一下吗?

**Comment by Ghs0my** [comment]
> > 已修复，请直接下载打包好的版本。 https://t.me/qiuchenlymac/471
> 
> 需要使用项目再次破解一下吗?

需要的

**Comment by SevenMrs** [comment]
> > > 已修复，请直接下载打包好的版本。 https://t.me/qiuchenlymac/471
> > 
> > 
> > 需要使用项目再次破解一下吗?
> 
> 需要的

好的, 我刚刚覆盖然后打开出问题了, 我去试一下
