### ISSUE TITLE
Bandizip 365  Finder 扩展 无法启动

### ISSUE THREAD

**Issue by wdkGitHub** [QiuChenly/InjectLib#69]
### 检查事项

- [X] 已确保 InjectLib 更新到最新版本
- [X] 已确保软件版本为 InjectLib 支持范围

### 描述问题

<img width="573" alt="image" src="https://github.com/user-attachments/assets/b7300351-ee08-427f-8086-405513c62f49" />
<img width="710" alt="image" src="https://github.com/user-attachments/assets/bcfce9dd-e0fd-4def-a23d-8a8c63b9e293" />

[执行 `pluginkit -e "use" -i "com.bandisoft.mac.bandizip365.findersyncextension"` 设置无效](https://www.bandisoft.com/bandizip.mac/help/finder-extension-sequoia/)

### 最小复现

`pluginkit -m  |grep com.bandisoft.mac.bandizip365` 找不到

### 系统情况

- [ ] SIP 开着还是关着？
- [ ] 是否为黑苹果（如果是黑苹果，请回答在下方标注为黑苹果的问题）
- [ ] 黑苹果是否amfi_getout_of_my_way开了？或者操作过amfi相关属性和amfi相关quirk？

### 系统信息

```Shell
OS: 15.2 (24C101)
SIP: 关闭
处理器 因特尔
```

### 期望行为

Bandizip 365  Finder 扩展 启动

**Comment by QiuChenly** [comment]
签名导致扩展无效。无法解决，这是系统限制。
