### ISSUE TITLE
运行启动脚本提示 Bad CPU type in executable

### ISSUE THREAD

**Issue by ugfly1210** [QiuChenly/InjectLib#8]
### 检查事项

- [X] 已确保 InjectLib 更新到最新版本
- [X] 已确保软件版本为 InjectLib 支持范围

### 描述问题

/InjectLib-main/秋城落叶_启动.command ; exit;
    minos 10.15
      sdk 14.5
Password:⚙️ 当前是 root 用户
sudo: unable to execute /usr/local/bin/python3: Bad CPU type in executable
zsh: rewriting /Users/ppp/.zsh_history would change its ownership -- skipped

Saving session...completed.

[进程已完成]

### 最小复现

在本人电脑必现

### 系统情况

- [ ] SIP 是否启动
- [ ] 是否为黑苹果（如果是黑苹果，请回答在下方标注了黑苹果的问题）

### 系统信息

```Shell
OS:macos sonoma 14.5 (23F79)
cache: 8GB
Core: intel core i5 2.4
```

### 期望行为

正常激活

**Comment by QiuChenly** [comment]
你自己安裝的python3的問題。
